version: '2'
services:
  vinny:
    build: .
    restart: always
    environment:
            - BOT_ID=<Bot ID here>
            - USE_DB=<True or False>
            - DB_PASSWORD=<DATABASE PASSWORD>
            - DB_SCHEMA=<DEFAULT DATABASE SCHEMA>
            - DB_URI=<DATABASE URI>
            - DB_USERNAME=<DATABASE USERNAME>
            - DISCORD_TOKEN=<Discord bot token>
            - NUM_SHARDS=<Number of shards (reccomended 1 per 1000 servers)>
            - OWNER_ID=<Owner ID>
  database:
    image: mysql:5.7
    ports:
            - "3306:3306"
    environment:
            MYSQL_ROOT_PASSWORD: <Root Password>
            MYSQL_DATABASE: vinny
            MYSQL_USER: <user>
            MYSQL_PASSWORD: <password>
